// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: bidistream/bidipb/bidi.proto

package bidipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Greeting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *Greeting) Reset() {
	*x = Greeting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidistream_bidipb_bidi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Greeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Greeting) ProtoMessage() {}

func (x *Greeting) ProtoReflect() protoreflect.Message {
	mi := &file_bidistream_bidipb_bidi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Greeting.ProtoReflect.Descriptor instead.
func (*Greeting) Descriptor() ([]byte, []int) {
	return file_bidistream_bidipb_bidi_proto_rawDescGZIP(), []int{0}
}

func (x *Greeting) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Greeting) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type BidiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *BidiRequest) Reset() {
	*x = BidiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidistream_bidipb_bidi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiRequest) ProtoMessage() {}

func (x *BidiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidistream_bidipb_bidi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiRequest.ProtoReflect.Descriptor instead.
func (*BidiRequest) Descriptor() ([]byte, []int) {
	return file_bidistream_bidipb_bidi_proto_rawDescGZIP(), []int{1}
}

func (x *BidiRequest) GetGreeting() *Greeting {
	if x != nil {
		return x.Greeting
	}
	return nil
}

type BidiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BidiResponse) Reset() {
	*x = BidiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidistream_bidipb_bidi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiResponse) ProtoMessage() {}

func (x *BidiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidistream_bidipb_bidi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiResponse.ProtoReflect.Descriptor instead.
func (*BidiResponse) Descriptor() ([]byte, []int) {
	return file_bidistream_bidipb_bidi_proto_rawDescGZIP(), []int{2}
}

func (x *BidiResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_bidistream_bidipb_bidi_proto protoreflect.FileDescriptor

var file_bidistream_bidipb_bidi_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x62, 0x69, 0x64, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x62, 0x69, 0x64,
	0x69, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x64, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x62, 0x69, 0x64, 0x69, 0x22, 0x46, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0b,
	0x42, 0x69, 0x64, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x62, 0x69, 0x64, 0x69, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x26, 0x0a, 0x0c, 0x42, 0x69, 0x64, 0x69, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x49, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x39, 0x0a, 0x0a, 0x42, 0x69, 0x64, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x11, 0x2e,
	0x62, 0x69, 0x64, 0x69, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x62, 0x69, 0x64, 0x69, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x62, 0x69,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x62, 0x69, 0x64, 0x69, 0x70, 0x62, 0x3b,
	0x62, 0x69, 0x64, 0x69, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bidistream_bidipb_bidi_proto_rawDescOnce sync.Once
	file_bidistream_bidipb_bidi_proto_rawDescData = file_bidistream_bidipb_bidi_proto_rawDesc
)

func file_bidistream_bidipb_bidi_proto_rawDescGZIP() []byte {
	file_bidistream_bidipb_bidi_proto_rawDescOnce.Do(func() {
		file_bidistream_bidipb_bidi_proto_rawDescData = protoimpl.X.CompressGZIP(file_bidistream_bidipb_bidi_proto_rawDescData)
	})
	return file_bidistream_bidipb_bidi_proto_rawDescData
}

var file_bidistream_bidipb_bidi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bidistream_bidipb_bidi_proto_goTypes = []interface{}{
	(*Greeting)(nil),     // 0: bidi.Greeting
	(*BidiRequest)(nil),  // 1: bidi.BidiRequest
	(*BidiResponse)(nil), // 2: bidi.BidiResponse
}
var file_bidistream_bidipb_bidi_proto_depIdxs = []int32{
	0, // 0: bidi.BidiRequest.greeting:type_name -> bidi.Greeting
	1, // 1: bidi.GreetService.BidiStream:input_type -> bidi.BidiRequest
	2, // 2: bidi.GreetService.BidiStream:output_type -> bidi.BidiResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bidistream_bidipb_bidi_proto_init() }
func file_bidistream_bidipb_bidi_proto_init() {
	if File_bidistream_bidipb_bidi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bidistream_bidipb_bidi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Greeting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidistream_bidipb_bidi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidistream_bidipb_bidi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bidistream_bidipb_bidi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidistream_bidipb_bidi_proto_goTypes,
		DependencyIndexes: file_bidistream_bidipb_bidi_proto_depIdxs,
		MessageInfos:      file_bidistream_bidipb_bidi_proto_msgTypes,
	}.Build()
	File_bidistream_bidipb_bidi_proto = out.File
	file_bidistream_bidipb_bidi_proto_rawDesc = nil
	file_bidistream_bidipb_bidi_proto_goTypes = nil
	file_bidistream_bidipb_bidi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	BidiStream(ctx context.Context, opts ...grpc.CallOption) (GreetService_BidiStreamClient, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) BidiStream(ctx context.Context, opts ...grpc.CallOption) (GreetService_BidiStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/bidi.GreetService/BidiStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceBidiStreamClient{stream}
	return x, nil
}

type GreetService_BidiStreamClient interface {
	Send(*BidiRequest) error
	Recv() (*BidiResponse, error)
	grpc.ClientStream
}

type greetServiceBidiStreamClient struct {
	grpc.ClientStream
}

func (x *greetServiceBidiStreamClient) Send(m *BidiRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceBidiStreamClient) Recv() (*BidiResponse, error) {
	m := new(BidiResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	BidiStream(GreetService_BidiStreamServer) error
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) BidiStream(GreetService_BidiStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidiStream not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_BidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).BidiStream(&greetServiceBidiStreamServer{stream})
}

type GreetService_BidiStreamServer interface {
	Send(*BidiResponse) error
	Recv() (*BidiRequest, error)
	grpc.ServerStream
}

type greetServiceBidiStreamServer struct {
	grpc.ServerStream
}

func (x *greetServiceBidiStreamServer) Send(m *BidiResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceBidiStreamServer) Recv() (*BidiRequest, error) {
	m := new(BidiRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bidi.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidiStream",
			Handler:       _GreetService_BidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "bidistream/bidipb/bidi.proto",
}
